default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# development:
#   <<: *default
#   # url: https://1ca6-194-33-45-162.ngrok-free.app
#   url: <%= ENV['DATABASE_URL'] %>
#   username: postgres
#   database: rootlydemobot
#   password: Test1234

development:
  <<: *default
  host: dpg-cgntdv8rddl9mmo4b0b0-a.oregon-postgres.render.com
  username: admin
  database: rootlydemobot
  password: pE3TH5XvijZ1gTfFBc3pd6IMHEnC8MBI

production:
  <<: *default
  host: dpg-cgntdv8rddl9mmo4b0b0-a.oregon-postgres.render.com
  username: admin
  database: rootlydemobot
  password: pE3TH5XvijZ1gTfFBc3pd6IMHEnC8MBI

test:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  username: postgres
  database: rootlydemobot
  password: Test1234
